# Dockerfile by Aaron Reed
# 
# Constructed based on README instructions from:
# https://github.com/sosuperic/MeanSum
# ______________________________________________

FROM pytorch/pytorch:0.4_cuda9_cudnn7
# RUN /workspace/src/setup.sh

# RUN git clone https://github.com/sosuperic/MeanSum
# RUN bash MeanSum/scripts/setup_dirs.sh
# RUN bash MeanSum/scripts/install_python_pkgs.sh
# RUN python MeanSum/scripts/update_tensorboard.py

# ENV MS_PATH /workspace/src/MeanSum
# ENV DATA_PATH .data
# 
# ENV YELP_DS ${DATA_PATH}/yelp/*
# ENV TOKENIZER ${DATA_PATH}/subwordenc_32000_maxrevs260_fixed.pkl
# ENV SUMR_MODEL ${DATA_PATH}/sum_e0_tot3.32_r1f0.27.pt
# ENV LANG_MODEL ${DATA_PATH}/lm_e24_2.88.pt 
# ENV CLASS_MODEL ${DATA_PATH}/clf_e10_l0.6760_a0.7092.pt
# ENV REF_SUMR ${DATA_PATH}/summaries_0-200_cleaned.csv 

# COPY ${YELP_DS} ${MS_PATH}/datasets/yelp_dataset/
# COPY ${TOKENIZER} ${MS_PATH}/datasets/yelp_dataset/processed/
# COPY ${SUMR_MODEL} ${MS_PATH}/stable_checkpoints/sum/mlstm/yelp/batch_size_16-notes_cycloss_honly-sum_lr_0.0005-tau_2.0/
# COPY ${LANG_MODEL} ${MS_PATH}/stable_checkpoints/lm/mlstm/yelp/batch_size_512-lm_lr_0.001-notes_data260_fixed/
# COPY ${CLASS_MODEL} ${MS_PATH}/stable_checkpoints/clf/cnn/yelp/batch_size_256-notes_data260_fixed/

# RUN bash MeanSum/scripts/preprocess_data.sh
